### ISSUE TITLE
Create GitHub webhook linked to Discord

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#101]
With all of the meeting resources we have on GitHub, it would be nice to have a feed of information from the repository into the community Discord, so that people will get notifications for new/closed issues, updates to documentation, and other items in the project management repository.

**Comment by whoabuddy** [comment]
Testing if a comment comes in after configuration.

**Comment by whoabuddy** [comment]
Closing out this issue as it appears to be functioning as expected! :octocat:

**Comment by lrettig** [comment]
Exciting! I love this sort of integration, thanks for doing this :)
