### ISSUE TITLE
Confirm that grant application is ready for submission

### ISSUE THREAD

**Issue by jennymith** [stacksgov/pm#102]
The Stacks [gov grant application](https://paper.dropbox.com/doc/Stacksgov-Grant-Proposal--A96OhBsQlTQzJM6ouMd3DlHiAQ-ke9qLunt5n7WwWwZTV56I) is one round of revision away from being ready to submit! Just waiting on clarification from @jcnelson regarding a small issue regarding voting mechanisms.

Assuming that issue is clarified soon, I propose that quickly review and prepare the submit the application during the governance call tomorrow, 10/22.

**Comment by jennymith** [comment]
**Updates from 10/22/20 gov meeting:**

- [ ] @joberding and @whoabuddy will add notes to revise budget and milestones for grant
- [ ] @jennymith will finalize revisions
- [ ] @joberding will submit grant application by the afternoon on 10/23/20

**Comment by joberding** [comment]
@jennymith I added comments to the Grant document based on our discussions during the governance call today.

**Comment by whoabuddy** [comment]
@jennymith I added my comments as well, and revised the budget and milestones section to reflect the changes. My version is between the `(WIP)` and `(end WIP)` blocks, and unless someone disagrees, should be ready to move forward!

**Comment by jennymith** [comment]
@whoabuddy Awesome work, Jason! I added a snippet toward the end and a couple tweaks but otherwise looks good to me. Over to @joberding for a final review before submitting!

**Comment by joberding** [comment]
@jennymith I added comments to the Grant document based on our discussions during the governance call today. 

> 
> 
> The Stacks [gov grant application](https://paper.dropbox.com/doc/Stacksgov-Grant-Proposal--A96OhBsQlTQzJM6ouMd3DlHiAQ-ke9qLunt5n7WwWwZTV56I) is one round of revision away from being ready to submit! Just waiting on clarification from @jcnelson regarding a small issue regarding voting mechanisms.
> 
> Assuming that issue is clarified soon, I propose that quickly review and prepare the submit the application during the governance call tomorrow, 10/22.

Reviewed this morning 10/23/2020. It is ready to go.

**Comment by whoabuddy** [comment]
Closing as the grant was submitted and feedback received via stacksgov/Stacks-Grants#27
