### ISSUE TITLE
Grant: Identify Team Members responsible for the delivery of the grant

### ISSUE THREAD

**Issue by joberding** [stacksgov/pm#106]
"We'd like to learn more about the team. Can you please update to include the team members names and roles who will be responsible for the delivery of the grant? 2-3 grant leads are fine, we just want to make sure there is clear accountability for the work here."
[Stacks Gov Grant Proposal Comments](https://github.com/stacksgov/Stacks-Grants/issues/27#issuecomment-721286621)

**Comment by jennymith** [comment]
Notes:
- Harold interested in leading voting mechanism project
