### ISSUE TITLE
Grant: Provide further details for Voting Mechanism

### ISSUE THREAD

**Issue by joberding** [stacksgov/pm#107]
"Voting Proposal

- M1 of the Community Voting Mechanism might start with a handful of voting mechanisms they want to consider.

- **M4 of making it open source software - who will be building that?** I see that Foundation Research Scientist Jude Nelson is listed here as a technical contributor, has he agreed to a set number of hours for this project? I know he is very busy and want to make sure there is a technical reviewer included in this grant who can commit the necessary time to the deliverables outlined above. If he is not available, would you be able to scope with someone else? Or remove the technical components of the proposal? It’s a lot of work to build - so could it start as non-software first? Especially for $450."

[Stacks Gov Grant Proposal Comments](https://github.com/stacksgov/Stacks-Grants/issues/27#issuecomment-721286621)

**Comment by jennymith** [comment]
Update from 11/05 meeting:
- Harold has volunteered to take the lead on this project
- There were no major objections to this during the meeting; should there be no major objections from the community, we would like to confirm this decision within the next week

**Comment by jennymith** [comment]
The grant proposal has been updated and we're now just waiting on a response from the review committee!

**Comment by jennymith** [comment]
The grant proposal has been updated and we're now just waiting on a response from the review committee!
