### ISSUE TITLE
Grant: Identify Lead for Code of Conduct

### ISSUE THREAD

**Issue by joberding** [stacksgov/pm#108]
"Code of Conduct

- Who will be leading this from the governance working group?"

[Stacks Gov Grant Proposal Comments](https://github.com/stacksgov/Stacks-Grants/issues/27#issuecomment-721286621)

**Comment by jennymith** [comment]
Update from 11/05 meeting:
- We will try to identify and confirm a lead for this asyc
- Some group members recommend @joberding for this role
