### ISSUE TITLE
Grant: Identify and confirm lead for Code of Conduct

### ISSUE THREAD

**Issue by jennymith** [stacksgov/pm#112]
This issue references issue #108.

- [x] Nominate potential leads in the comments below by 11/10
- [x] Discuss options here or on [Discord](https://discord.com/invite/ny6wGkx)
- [x] Confirm lead by 11/13

**Comment by whoabuddy** [comment]
@joberding volunteered here! :smile: https://github.com/stacksgov/pm/issues/105#issuecomment-722627924
