### ISSUE TITLE
Grant project management

### ISSUE THREAD

**Issue by jennymith** [stacksgov/pm#119]
- Figure out weekly goals
- Publish project boards for each workstream on GitHub
- How best to notify the community that this work has started - forum? Discord?
- What can we realistically finish by the end of Q4 2020?

cc: @joberding @HaroldDavis3

**Comment by HaroldDavis3** [comment]
@jennymith Thanks for organizing this. Seems both Discord & Forum would be best. All for keeping up Gh project board updates too. 
### This week 

- [ ] Currently reaching out to [Amy Zhang](https://github.com/amyxzhang) of PolicyKit. Hoping she'll have some insights for us on a likely timeline and more. 

- [ ] Tomorrow - Tinkering w/ Friedgers OI chat & PolicyKit as is. They have templates that will require limited technical know how, which conveniently overlap with Jude's original ideas of quorums, date, time triggers etc. 

If possible with OI chat's Discord bridge, as opposed to Discord alone, we can even pull off Gaia hub & Auth integrations he [mentioned](https://docs.google.com/presentation/d/1hyxiNFp716T1TOqx1QjLmqDw2OnfPgxmp33Ud4dOCTI/edit#slide=id.g96326f23bb_0_31) too. If we are pressed for time later on, this tinkering will pay off if we want to use policy kit w/out OI chat.
### Next Week

- [ ] Will update project boards with results of said tinkering.

- [ ] Begin Discussion on other testing approaches promised in grant app.

- [ ] Publishing discussion results for further input.

**Comment by joberding** [comment]
Here is my current (in-process) project [overview](https://docs.google.com/document/d/1eYJhrZhmqt9RcTJ-PkzRlzgt0Yl1d2tgjDj24SN2Mfs/edit?usp=sharing). Updates will be ongoing. Comments are welcome.

### Action List
Week of 7 December 2020

- [ ] Research and comprehensive review of existing relevant codes of conduct including [Contributor Covenant](https://www.contributor-covenant.org/)

- [ ] Develop RFC for community input regarding key questions and code of conduct (COC)

- [ ] Review and selection of tools for transparent reporting and project managment

**Comment by joberding** [comment]
### Overall Management of Project
**Completed Tasks**

1.  Email sent to the Stacks Foundation requesting contract documents (3 December 2020).

**Comment by whoabuddy** [comment]
Closing because tracked in other related issues.
