### ISSUE TITLE
Extend call to 90 min

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#12]
On [last week's call](https://github.com/stacksgov/resources/issues/12), Lane mentioned extending the meeting from 60 minutes to 90 minutes. I think as this topic of governance continues to expand the extra time will be helpful.

I could see this working one of two ways, and I would love to know everyone else's input:

A) We could update the agenda to cover 90 min worth of material.

B) We could keep the agenda high-level, designed to be done in 60 min, and save discussion for final 30 min.

Thoughts? Changes?

**Comment by lrettig** [comment]
My inclination is to leave the official call length at 60 mins, and try to cover the most important agenda items during those 60 mins, so as to be respectful of everyone's time, but also establish a norm that the call can run over for those who can stay. Basically, front-load the agenda and push longer "discussion" items to the end.

Okay, I think I'm agreeing with your proposal "B" above :)

**Comment by blocks8** [comment]
Agreeing with #2 too, thank you for putting this togetheer!

**Comment by lrettig** [comment]
This was discussed on the past two calls. We decided to keep call length at officially 60 mins, but can have a list of "overflow" topics for folks who want to stick around longer. The Zoom software we're using facilitates this: the host can hand hosting to someone else, and the cloud recording should be uninterrupted.

I don't think there's anything to do here right now - please reopen if I've missed something!

**Comment by whoabuddy** [comment]
This may be an issue depending on who hosts if we don't setup a shared account via #14, the free plan meetings are limited to 40min. (not even 60min!)

**Comment by lrettig** [comment]
I can set up the call on my account, and either initiate the call, or else
list someone else as the host - for now. But agree we'll want #14.

>
