### ISSUE TITLE
Gathering key community issues through the next Stacks Town Hall

### ISSUE THREAD

**Issue by jennymith** [stacksgov/pm#138]
We're in the process of planning the next Stacks Community Town Hall, which will serve as a space for community entities to share updates, as well as a forum for stakeholder representatives to surface key issues facing the global Stacks community. 

This is also an opportunity for community board representatives @joberding and Sean Gonzalez to identify issues worth pursuing with the Stacks Board. Before we do that, we need to tackle the following:

- [x] Stacksgov group decide on date of town hall: March 31st (end of month) or April 2nd (usually more attendees on a Friday)
- [x] @jennymith Set up town hall on Crowdcast and promote to community by 03/19
- [x] Stacksgov group identify representatives for various stakeholder groups, e.g. miners, developers, Stackers, etc. by 03/18
- [x] @jennymith Contact and confirm representatives for town hall updates by 03/26
- [ ] @joberding and Sean should be available for introductions to representatives before town hall
- [ ] @joberding should be available to give an introduction to the Community Board Seat on the town hall

**Comment by jennymith** [comment]
Here are the stakeholder groups we have confirmed so far:
- Stacks Turkey
- Stacks Pakistan
- Stacks China
- Stacks Korea

Stakeholder groups for which we need representatives:
- Miners
- Developers
- Stackers (Stacking pools)

What other groups are we missing?

**Comment by whoabuddy** [comment]
Related to #68?

**Comment by joberding** [comment]
@jennymith Another group is the folks who are building within the ecosystem- including grantees, creatives, devs and entrepreneurs/entities like freehold, daemon, blocksurvey, etc.  Friday sounds good if that attracts more people, but either works for me.

**Comment by jennymith** [comment]
Town hall has been scheduled for 04/02 at 10:00am EST / 2:00pm UTC. @joberding and Sean, just copied you both on an email listing all the potential stakeholder reps.

**Comment by whoabuddy** [comment]
Closing since Town Hall passed -thanks everyone!
