### ISSUE TITLE
Bounties for recurring tasks

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#145]
## Discussion Item

We've talked about this before and it came up again in #144, with the ongoing work to maintain the repo, create notes, and publish updates, it would be great to explore how these kind of tasks could be funded by bounties in STX.

Tagging some related issues as well: #136, #81, #80

I'm also wondering if this has some overlap with the sourcecred and policykit work being done by @HaroldDavis3 and @hozzjss in #129.

These activities are important for both transparency and public awareness of our efforts - so they'd be worth a decent amount of cred in my opinoin!

**Comment by joberding** [comment]
+1 on overlap with sourcecred and policykit.

**Comment by whoabuddy** [comment]
Could use a different instance of the same structure we use with advocates, and follow a similar props/didathing/meeting-notes type model that defines a Stacking pool to fund it. WIP - keeping this open for additional updates as they come out.

**Comment by HaroldDavis3** [comment]
tagging issue #129 for most recent updates for this discussion.

**Comment by whoabuddy** [comment]
Closing out in favor of #181 and the use of [Dework](https://dework.xyz)
