### ISSUE TITLE
Demo PK-MG-SC integrations

### ISSUE THREAD

**Issue by hozzjss** [stacksgov/pm#147]
## Demo for Governance tools
That would include policy kit, a place to author and vote on policies for a community, metagov a governance engine or a collection of apis that help execute actions that should be side effects or actions of a governance process, and sourcecred a tool for tracking value creation and exchange within a community and also how that value determines the payouts for a certain week

The current governance process is almost non-existent and having a way to represent people in a fair way is essential for community cohesion and inclusion, policykit wraps around discord and can read how many thumbsup reactions are on it and based on that and after counting the total votes could propose a new moderation rule that prevents profanity in message or deletes messages with high toxicity, this also can be a smart contract call on chain as a representative of the will of the people so that people don't even need to have stacks to participate.

With sourcecred you can define what brings value to your community and give it an actual score and through that score you can determine someone's created value or given value in the community, their reputation, and you can even make even more complex interactions if you incorporated in the decision making process for example can have some huge effects in showing what the people with the most value created want, not even with incorporating it into the decision making mechanism, it's still powerful if it's visible what these value creators want.

**Comment by joberding** [comment]
Do you want to set up a formal demo via Zoom or Crowdcast that will be promoted to the community as a whole?

**Comment by hozzjss** [comment]
Let’s keep it formal for now until we’re sure we wanna bring it to the community, if we are sure however and have settled on what we wanna do with it, then we can have a crowdcast

**Comment by joberding** [comment]
Any thoughts on a date? Just making sure we are on target for another demo.

**Comment by hozzjss** [comment]
I'm thinking July after I finish my exams, first Wednesday in July?

**Comment by joberding** [comment]
sounds good - july 7th. time?

**Comment by hozzjss** [comment]
10 AM PST or earlier would be great

**Comment by whoabuddy** [comment]
@jennymith to help with coordination when ready!

**Comment by hozzjss** [comment]
I think I'm ready and maybe we could have it on Thursday next week, maybe some other time next week as well but I prefer either Thursday or Friday

**Comment by whoabuddy** [comment]
Closing for now - will be part of the work at the Governance Lab.
