### ISSUE TITLE
Governance Lab/Initiative

### ISSUE THREAD

**Issue by jennymith** [stacksgov/pm#149]
I'm currently fleshing out an initiative to fund a governance lab/working group/unit dedicated to developing a sustainable governance model for the Stacks Ecosystem. I assume @HaroldDavis3, @hozzjss, and @joberding would want to take the lead here! The idea is still early and could use lots of input from this working group and from the broader community but some thoughts I had include:

- Publishing a governance roadmap so that the community can better follow our work and look forward to concrete deliverables
- Actual partnerships with communities like SourceCred to develop tools we can use ASAP
- Gov lab could help manage the SIPs process and CABs?

**Comment by joberding** [comment]
I’m in. Can the four of us have a mtg on this? Sorry for not being in mtg today.

**Comment by HaroldDavis3** [comment]
Here are our most recent notes on this WIP. https://docs.google.com/document/d/1IMPqmlV2_48gR7wOz6BUlJD0TwYDf3mTer6a_5pynQ4/edit?usp=sharing
@joberding feel free to work your outreach magic mentioned this morn on what we have so far :)

**Comment by joberding** [comment]
@HaroldDavis3 Great work! Unfortunately, I can't be the communications person for this project. That type of outreach is very time consuming. I'm focusing on my own research projects atm. I think @jennymith mentioned hiring someone for the governance lab and @hozzjss has a contact who is interested.

**Comment by joberding** [comment]
Here is a proposal for structure of the gov Lab that I am working on: 
https://docs.google.com/document/d/1Kh2xFFhUg1cCjYTWFYzA56Veq-m522Gytq6ygtm8hjM/edit?usp=sharing

@jennymith @HaroldDavis3 @Hozzjss  Take a look. Feel free to add comments.

**Comment by hozzjss** [comment]
This all looks really good, I appreciate the thought and work put into it, thank you so much for all this work @joberding I'm seeing this as the seed and a very good one for the focus of our work, and I think we'd use it and expand on it as we go on

**Comment by whoabuddy** [comment]
Tagging #56 for relevant information related to our original discussion!

**Comment by HaroldDavis3** [comment]
Update on Gov Lab work from Ryeder!: https://www.notion.so/35689c7e912842b59984703ba167be86?v=4619022c15f74bdc8b5c13717ba352ec
