### ISSUE TITLE
Share YouTube account

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#15]
I'm currently the only person with access to the Stacksgov account and [channel](https://www.youtube.com/channel/UCirhluDUpSPVMZQn210HETg) on YouTube, which hosts the call videos. We should give others access to this account.

**Comment by whoabuddy** [comment]
I would like the option to access, download, and store videos in addition to accessing them on Youtube, and it might be a good use case for a Stacksgov-owned [xordrive](https://xordrive.io/) account or similar to store the content.

**Comment by lrettig** [comment]
Feel free to set something up, and I can dump all the raw files there.

**Comment by whoabuddy** [comment]
Actually, that brings up a bigger thought/topic, can Stacksgov own a Blockstack ID that people can share? Creating something and handing out the key is easy, but revoking access would be a whole different issue, plus we would all have to shuffle logins between that ID and our own sets. Something to ponder. :thinking: 

The alternative is to have multiple community members create an account and host info, but that also feels like it would get messy over time. I wonder if we can designate someone to hold the "main" and someone to hold the "backups" similar to designating a host for the meetings. 

I also wonder if someone would donate hosting to this purpose, but I am sure the directory size will creep up as we do more recorded calls. They seem to be fairly small for the content though (especially without video). I will see if I can offer anything in this regard as well, and I am open to other ideas. Stacksgov-owned Netlify? How far do we want to take this? :muscle:

**Comment by lrettig** [comment]
I added @whoabuddy and @joberding as managers of the YouTube channel today, so the original task here is complete. I'll leave this open for now as there are a few other questions and ideas in this thread.

**Comment by whoabuddy** [comment]
Closing in favor of #33
