### ISSUE TITLE
Working Group Call #5

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#16]
Date/time: Wednesday, March 25, 2020, 7am PT/10am ET/2pm UTC/3pm CEST/10pm CST ([time zone conversion](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Stacks+Governance+Working+Group+Call&iso=20200311T10&p1=179&ah=1))
**Note the recent timezone changes. Please double-check the time of this call in your locale using the above link!**
Location: Link will be posted in [#governance working group channel](https://discordapp.com/invite/ny6wGkx) on Discord shortly before the call
Recording: https://youtu.be/gpw6byKPeIw

If you'd like to be added to the recurring calendar invitation, please DM me your email address on Discord.

Proposed agenda (feel free to amend!):
- Quick round of intros
- What happened over the past week?
  - Resources (YouTube/GitHub/Discord/Discourse/others)
  - Regular updates
  - One on one "stakeholder interviews"
- Standup!
  - What is everyone working on right now?
  - Any blockers?
  - What will happen over the next week?
- Project logo (Jason's #10)
- Community survey
- One-on-one interviews and notes
- Preliminary governance proposal
- Stacks Foundation update (from PBC)
- Any other updates?
- How to get involved/contribute
  - Resources
  - Regular updates
  - Survey
- Next/recurring call schedule
  - call length and proposal to extend to 90 min (#12)
  - call for other stewards/github maintainers
- Time allowing: Harold to discuss indigenous nations and matrilineal governance structures

**Comment by whoabuddy** [comment]
I created issue #17 for the topic of a "community observer" from Discord, and we should add it to the agenda as well!

**Comment by lrettig** [comment]
There's a Blockstack Community Townhall call on the Stacks 2.0 Testnet this week that overlaps with our usual call time (it starts at 9:30 EDT). Should we move the governance call back 30 or 60 mins?

https://community.blockstack.org/townhall-testnet

**Comment by joberding** [comment]
Move back 60 minutes or cancel this week

**Comment by whoabuddy** [comment]
An hour earlier is _pretty early_, but I'm willing if everyone else votes for the same.

**Comment by joberding** [comment]
I meant move forward - it would be way to early for me in CA

**Comment by whoabuddy** [comment]
@lrettig @joberding - looks like the town hall was rescheduled to April, so we can keep things as-is and meet at the normal time.

![2020-03-24 09 52 14 community blockstack org 838ff942bfbe](https://user-images.githubusercontent.com/9038904/77454030-3d1c6280-6db5-11ea-9d49-a9249d9aa087.png)

**Comment by lrettig** [comment]
Closing in favor of #19
