### ISSUE TITLE
Establish community observer role for Blockstack PBC research calls

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#17]
Based on a recommendation from @dantrevino in Discord, there is an interest in having community involvement as Blockstack PBC works on establishing the initial foundation structure in order to provide visibility and representation.

@dantrevino nominates @joberding to participate as a "community observer" on Blockstack PBC research calls.

Please comment with any feedback on the items above, additional thoughts, or any additional nominations.

**Comment by dantrevino** [comment]
Thx @whoabuddy.  The only other input I have is that ideally this could start today, not wait for a call next week.

**Comment by whoabuddy** [comment]
Agreed - just wanted to get an official placeholder both for the issue, and for the agenda item so we can ideally talk about _progress_ versus _getting started_ :slightly_smiling_face:

**Comment by whoabuddy** [comment]
Can we close this issue? I know the idea was approved but not sure if there is an additional action necessary here. @joberding @lrettig

**Comment by njordhov** [comment]
The decision should be in the official record on github and included in processes, not only mentioned on discord and in a closed issue.

**Comment by whoabuddy** [comment]
Closing in favor of #66 as the foundation is already formed, and a community board seat would be the best mechanism for community involvement / representation at this time per our discussion during #113.
