### ISSUE TITLE
Community Funding Streams

### ISSUE THREAD

**Issue by HaroldDavis3** [stacksgov/pm#173]
## Discussion Item
Including this discord discussion from Phillip.xck.app#1157: https://discord.com/channels/621759717756370964/675389252816732166/949057849277952030  

> Hi friends, I am a bit worried that the funding programs for our Stacks Community (ie accelerator and the NFT minting) are a bit blinded to select projects led by founders that have been loyal to design and build apps using Stacks infrastructure. Not only that, also blindness to projects that are reaching other parts of the world.  One true fact is that the blockchain has proven, said by financial institutions worldwide, central banks, World Bank, etc, it is that blockchain facilitates crossborder value transfer.  The rest of the applications or utilities still have to be proven by the general public.  That is the value proposition that the Stacks community is trying to develop!  It is being developed, so nobody has the final word yet what is succesful!  It is very good to bring talent from out of the community to help in the decisions of community development matters, probably their success was made in another environment, but my main concern is that the leit motiv or the Stacks inspiration of the community is not consolidated and the way they make decisions does not consider the community participation.   I am worried that founders and teams (me and other founders that I know) that have been loyal to the Stacks community, as they do not see some funding support, they are going to be forced to look into other chains that are providing it, taking all that was learnt here at Stacks in the commercial, community and technical aspects to the other communities.

**Comment by Jolie-Ze** [comment]
This is really interesting, has this been discussed yet?

**Comment by HaroldDavis3** [comment]
Will comeback once contact with Phillip is made.
