### ISSUE TITLE
Community Mining Initiatives

### ISSUE THREAD

**Issue by HaroldDavis3** [stacksgov/pm#177]
## Discussion Item

The following discussion points were brought up by runefar#8701 in our AdvoxDAO server: 
> May not have been my best discussion, but there is a valid concern being brought up here by multiple members of our community around the lessening amount of miners.  Is there any efforts we as a community should be doing to better ensure an increase of miners or at least a change in perspective on the issue? When it comes to stack grants should we be putting more community focus on projects that may benefit solving problems such as this that could affect the system in the long term weather it be through a specific focus on the miners as part of their project or miners being indirectily involveled in some element of their project(such as it being a later stage funding mechanism for them or a functional component in a dual bitcoin stacks part of say a renewable based project)? What do you guys think of this problem and the impact as well as focus it should have put on it? https://discord.com/channels/621759717756370964/728030782693834862/949969227488575488

**Comment by Hero-Gamer** [comment]
I remember hearing the blockchain dev's opinion that in general, Stacks price going up is basically the only way to attract more miners, as it becomes a more profitable thing to do. Tho there are probably many aspects in addition to profits, such as barrier to get started to mine. I believe I hear them say with Stacks network 2.1 will allow people to mine more easily (less barrier/cost to entry). Not sure if it helps to resolve this immediately, just wanna put some points down on paper and get the convo going.

**Comment by Jolie-Ze** [comment]
This item was addressed in the last call on 5/12/22 and will be available [here](https://resources.stacksgov.com/#/calls/) once the recordings are updated

**Comment by HaroldDavis3** [comment]
This [link](https://youtu.be/NLT1OJwCa0k?t=4488 ) starts at a response from Jude to this particular discussion.

**Comment by whoabuddy** [comment]
Closing out given the responses above, please re-open if more discussion is needed!
