### ISSUE TITLE
Core stakeholder interviews

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#2]
The first three of these are scheduled over the next couple of weeks. More to follow!

These are being added to resources at stacksgov/resources#23

**Comment by lrettig** [comment]
Conducted first interview today. Learned a lot! Will clean up notes and share.

**Comment by lrettig** [comment]
Second interview conducted. Still working on cleaning up and sharing the notes from the first two calls. One more call is scheduled, more coming soon. Feel free to nominate participants!

**Comment by njordhov** [comment]
Looking forward to the notes.

**Comment by lrettig** [comment]
Two more scheduled! You can nominate interviewees here: https://forms.gle/Zf4sBtBSE6Dy7rzb9.

**Comment by lrettig** [comment]
Conducted fourth interview today, and there's another tomorrow. Received a bunch of nominations of other folks in the community to speak to. I will continue to reach out to them and schedule more chats. I haven't cleaned up and shared notes from any of the calls yet, but I'll begin working on this.

**Comment by lrettig** [comment]
Fifth call done. Began working on cleaning up and sharing notes with interviewees. I plan to release them anonymously, but I think it would be fairly easy to "deanonymize" many of them based on the content. I'm pondering what to do about this. One option is to slice them up and release sets of answers for each question, independently. Another is to do some higher-level analysis on the interviews and release that instead. Let me know if you have better ideas!

**Comment by lrettig** [comment]
As of today, seven calls done, and I've cleaned up and shared the notes for three of them (with the interviewees only so far). I have one more call scheduled this week.

**Comment by lrettig** [comment]
Eight calls done, cleaned up and shared notes for five. I think I have a lot of material for now, so I'm going to put new calls on hold for the time being until I/we have had a chance to process the information we've collected so far.

**Comment by lrettig** [comment]
Cleaned up and shared all notes. Got approval to publicly post four of these, and should have more soon. Will begin sharing them ASAP.

**Comment by lrettig** [comment]
I've begun posting these at https://github.com/stacksgov/resources/tree/interview-notes/interviews

**Comment by lrettig** [comment]
Finished editing and posted all notes. This concludes the current round of interviews.
