### ISSUE TITLE
Document PM best practices

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#20]
Let's document some PM-related practices & procedures here:

- [x] How to host the weekly call (setting up zoom, sending invitations, managing the agenda, sharing the video and notes, etc.)
- [x] How to write and publish a regular update
- [x] How to use/manage this GitHub org.

**Comment by whoabuddy** [comment]
From uploading the Youtube video today, here are the defaults:

__Video Name:__

Stacks Governance Call #X [YYYY/MM/DD]

__Video Description:__

Links shared on call:
- Link 1
- Link 2
- Link 3

_side note: should we put a canonical reference to the github repos on each video, or in the description of the org?_

__Video Tags:__

blockchain, governance, blockstack, stacksgov

**Comment by lrettig** [comment]
> should we put a canonical reference to the github repos on each video, or in the description of the org?

Why not both?

**Comment by joberding** [comment]
> 
> 
> Let's document some PM-related practices & procedures here:
> 
>     * [x]  How to host the weekly call (setting up zoom, sending invitations, managing the agenda, sharing the video and notes, etc.)
> 
>     * [x]  How to write and publish a regular update
> 
>     * [x]  How to use/manage this GitHub org.

Are we currently using the Blockstack Zoom or our own dedicated Zoom channel? I think that this is a great idea to capture processes so others can jump in and help.

**Comment by lrettig** [comment]
> Are we currently using the Blockstack Zoom or our own dedicated Zoom channel? I think that this is a great idea to capture processes so others can jump in and help.

For now, it's my account - we also used the Blockstack zoom account once, when Jenny set up the meeting for us. In #14 we're discussing setting up a new zoom account dedicated to stacksgov.
