### ISSUE TITLE
Proposal for SIPs process

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#22]

**Comment by lrettig** [comment]
I have an early draft of this, based on research I've done on the BIP, EIP, and ZIP processes, as well as on the existing SIP process:

- https://github.com/bitcoin/bips/blob/master/bip-0002.mediawiki
- https://github.com/zcash/zips, https://zips.z.cash
- https://eips.ethereum.org/EIPS/eip-1, https://eips.ethereum.org/
- https://github.com/blockstack/stacks-blockchain/blob/master/sip/sip-000-stacks-improvement-proposal-process.md

**Comment by whoabuddy** [comment]
Issue #17 is a good candidate for our first one :slightly_smiling_face:

**Comment by whoabuddy** [comment]
Closing as this was also addressed in https://github.com/stacksgov/proposals/issues/1 and the SIPs have already been moved from blockstack/stacks-blockchain to stacksgov/sips.
