### ISSUE TITLE
Create a project for "Blockstack Community Governance" blog post

### ISSUE THREAD

**Issue by blockstackers** [stacksgov/pm#26]
A project may make it easier to manage this workflow even if it's a fairly short-term project.

**Comment by whoabuddy** [comment]
I created a project [titled "Blog Post"](https://github.com/stacksgov/pm/projects/2) based on our conversation during the last meeting, and we can look at how to best structure it to help build content for our first (and subsequent) posts!

**Comment by whoabuddy** [comment]
Closing in favor of [project board](https://github.com/stacksgov/pm/projects/2), future issues will outline additional tasks!
