### ISSUE TITLE
Call for written contributions: What does the governance working group hope to achieve?

### ISSUE THREAD

**Issue by blockstackers** [stacksgov/pm#28]
Consider the following when providing your answer:

- What are the official goals of the governance working group? (I.e. Publish a governance proposal)
- What are the community goals of the governance working group? (E.g. Establish a community/stakeholder voting process?)
- Describe the short-term vs. long-term vision for the governance working group.

**All answers will contribute to a longer form blog detailing the work that this group has done on governance so far. (Pending review and approval from group members, of course.)**

**Comment by lrettig** [comment]
I'm not going to distinguish between "official" and "community" goals - I'm just going to list my goals here.

- What are the goals of the governance working group?

    - Agree on some fundamental basics such as a statement of shared values, basic principles, etc. (what I've been referring to as "foundational documents")
    - Publish a comprehensive, high-level governance proposal that aligns with our values and that we have rough consensus on, among the working group participants and the broader community
    - Increase the overall degree of awareness of, and interest and participation in, governance in general and the initiatives of the working group specifically
    - Design and launch some concrete initiatives such as a revised SIP process, a grants program, App Mining 2.0, etc.
    - Clearly delineate the roles and responsibilities of stakeholder bodies such as PBC, the Foundation, the working group, etc. vis-a-vis the overall ecosystem, and define the "scope of governance"
    - Put in place good processes, policies, and procedures to ensure the longevity of active, participatory, healthy governance
    - Make sure that all legitimate ecosystem/community/network stakeholders have equal opportunity to make their voice heard, and to get involved in governance

- Describe the short-term vs. long-term vision for the governance working group.

Short term: Keep up the good work we've been doing! Getting slightly broader participation in the community, doing a better job of communicating the things we have accomplished and our plans going forward, launching some new, concrete, constructive initiatives such as new SIPs process/grants program.

Long term: This will probably sound a bit "fuzzy" but have a sustainable, participatory system of governance that all or nearly all ecosystem participants view as legitimate, enfranchise as many stakeholders as possible and make sure they feel that their voices are heard and their needs are being considered, and accomplish all of this without entrenching a small group of elites and without too much bureaucracy :)
