### ISSUE TITLE
Call for written contributions: Describe the work that this group has undertaken, in detail.

### ISSUE THREAD

**Issue by blockstackers** [stacksgov/pm#29]
Consider the following when providing your answer:

- What processes did you have to establish in order for this group to run smoothly?
- What are the weekly calls for and how are they structured?
- How do group members utilize GitHub to manage projects?
- Who sets priorities for the group? Who oversees and maintains progress?
- How did you go about getting more engagement from the wider community?
- What exactly are you working on right now?
- What do you expect to achieve, in the next few weeks, from your current work?

**All answers will contribute to a longer form blog detailing the work that this group has done on governance so far. (Pending review and approval from group members, of course.)**

**Comment by whoabuddy** [comment]
Here are some of my answers and observations!

**What processes did you have to establish in order for this group to run smoothly?**

A framework for the flow for information, with GitHub becoming the central source for resources and action items. In the early stages we had information spread across the forum and Discord, and [a list of the commits](https://github.com/stacksgov/resources/commits/master?after=6a32bedd37b1a038c98160e8f9642c7cba5e46b4+104) show how things changed in Resources over time.

Fast-forward to now and we have:
- two project management boards ([phase one](https://github.com/stacksgov/pm/projects/1) and [blog](https://github.com/stacksgov/pm/projects/2))
- several open issues available for comment ([resources](https://github.com/stacksgov/resources/issues), [pm](https://github.com/stacksgov/pm/issues), [proposals](https://github.com/stacksgov/proposals/issues))
- a rolling [set of issues for calls](https://github.com/stacksgov/pm/issues?q=is%3Aissue+label%3Acall+)
- a set of [Standard Operating Procedures](https://github.com/stacksgov/pm/blob/master/sop.md) for those who want to get involved and [manage the repo](https://github.com/orgs/stacksgov/people) or help with recurring tasks
- a canonical [meeting and notes reference](https://github.com/stacksgov/resources/tree/master/calls) updated after each meeting
- a basic ["brand icon"](https://github.com/stacksgov/resources/blob/master/brand/stacksgov_greensquare_150x150.png) to use throughout the repo, Youtube, and other outlets
- an extensive [list of resources](https://github.com/stacksgov/resources/blob/master/README.md) provided by the community
- a set of [one-on-one interview notes](https://github.com/stacksgov/resources/tree/master/interviews) based on calls between @lrettig and stakeholders in the Blockstack ecosystem
- a survey that continues to see an uptick in responses and is near ready for review

**What are the weekly calls for and how are they structured?**

- See [stacksgov/resources/calls](https://github.com/stacksgov/resources/tree/master/calls)

**How do group members utilize GitHub to manage projects?**

- Mostly by creating issues, which are a placeholder for anything such as an idea, an actionable item, a discussion point, or a challenge/blocker. Issue labels and project boards are available to help group issues.

**Who sets priorities for the group? Who oversees and maintains progress?**

There is a running set of agenda topics each week, which dovetail into the work Lane is doing as part of the initiative. Anyone is welcome to add to the agenda in the week before the meeting, and we are working out a formal process to make sure items filed as issues are addressed and closed out where possible.

The agenda includes a basic stand-up of what I did over the week, what I plan to accomplish this week, and any blockers. This part of the meeting usually goes quickly, but I think it helps to maintain accountability on what people are working on as well as bring awareness to any challenges.

At this time myself, Lane, and Juliet coordinate each week for who wants to host the meeting, however hosting is open to anyone from the community and encouraged.

Brittany also gives an update from PBC about the foundation each week, which in these early stages is a big component in understanding how we, as the community, can interact and work with the governance initiative.

**How did you go about getting more engagement from the wider community?**

Within Blockstack, the goal is to keep putting out consistent content and updates, such that the community can keep up with what's going on with the group asynchronously if desired.

Outside of Blockstack, by being open and encouraging everyone to take part no matter their background, and doing our best to provide easy to digest resources for newcomers.

**What exactly are you working on right now?**

#29 :stuck_out_tongue: 

Throughout the week I typically look through the GitHub repos and check for:

- resources that can be updated from Discord or the forum
- past issues to include in this week's agenda
- open issues for general cleanup based on our standards, such as this one for [creating canonical note references](https://github.com/stacksgov/resources/issues/15)

**What do you expect to achieve, in the next few weeks, from your current work?**

To help outline and highlight the excellent work done by this group through a blog post, and to continue to grow the community around Blockstack as we try to identify the best way to handle the topic of **Governance**. _It's a doozy!_

**Comment by lrettig** [comment]
- What processes did you have to establish in order for this group to run smoothly?

Project management here on GitHub :), weekly working group calls, publishing the recording and notes from those calls in a permanent, open location so they're accessible to everyone. In a slightly less formal and structured manner, we also have lists of proposals and have asked community members to review them and share their thoughts (whether in writing or on the calls), we have the survey, and the one on one interviews.

- What are the weekly calls for and how are they structured?

They serve several distinct purposes: they're a standup (an opportunity for everyone in the working group to share what they've done, what they'll do next, and where they're blocked/need help), they're a chance for the different groups of stakeholders (PBC and the community, and now the Foundation) to sync on outstanding questions/issues/progress/etc., they represent a "checkpoint" for tracking overall progress on the governance initiative, they're a forum for reviewing "official" tasks and assignments and action items (i.e., project management), they're an open forum for people to share and discuss thoughts/questions/ideas/etc., and they are also a way to record all of these things for posterity and accountability purposes.

- How do group members utilize GitHub to manage projects?

Anyone may open an issue at any time - and issues can capture ideas, specific tasks, things to look into or remember, longer-term project proposals, process/project management things, etc. We also have a set of "canonical" documents, a knowledge base, that includes standard operating procedures for governance PM work, governance proposals, etc. that anyone may contribute to with a PR. On top of this, there are project boards (kanban-style boards) that can be used to track projects, such as crowdsourcing and authoring this blog post!

- Who sets priorities for the group? Who oversees and maintains progress?

It's emergent :) Priorities emerge from dialog among different participants, and the stakeholder groups outlined above. So far, I think we've done a good job of agreeing on a set of shared values, being values-driven in our approach to governance, and thus getting on the same page wrt priorities, but we could be more explicit about this in the future. I'd say all working group participants oversee progress - and probably other stakeholders who aren't active in the working group, such as the PBC board and leadership.

- How did you go about getting more engagement from the wider community?

So far we've had a pretty scattershot approach: forum posts, emails, GitHub, Discord, Twitter, YouTube, etc. In the future we could probably be more targeted and focus on channels that we know work well.

- What exactly are you working on right now?

Proposals for some concrete first tasks for the newly-formed Foundation, such as stewardship of the SIPs process, and launching a grants program.

- What do you expect to achieve, in the next few weeks, from your current work?

Hopefully, finishing those tasks I just described! I'd like to see these processes - SIPs, and grants, to be concrete - get to a place where, if I were to disappear, they would "run themselves" well :)

**Comment by joberding** [comment]
These are some of the areas that the Governance Working Group has been developing and discussing.
[Development of Resource hub for the community](https://github.com/stacksgov/resources/blob/master/README.md)
Governance Community Survey
Stakeholder Interviews
Foundation development and proposals
[Governance SIP protocol](https://docs.google.com/document/d/1huF3u6BlrEapbjw77wGp_lq3d3kC17ZugCalvpN8M3U/edit#heading=h.fehdjdjgdpew) 
Creation of a community observer role
Code of Conduct issue: Governance and Due Process

Information and resources  on some of these issues can be found on the [April 29th Governance Working Group Update](https://forum.blockstack.org/t/governance-working-group-update-april-29-2020/10754)
