### ISSUE TITLE
Record official action items

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#36]
This was brought up on call 10 (#35), regarding the community observer role (#17). As I mentioned on the call, we began recording an official list of "decisions" and "action items" on each of the Ethereum calls, which has been quite helpful - see [here](https://github.com/poojaranjan/pm/blob/ee277386af75621c48923f9740e4913ee241cd05/All%20Core%20Devs%20Meetings/Meeting%2085.md#summary) for an example. Each new call begins with a review of the action items from the previous call.

Is this something we want for our meetings?

**Comment by KieranAlexis** [comment]
Looks like a great way of doing things imo.

**Comment by joberding** [comment]
I reviewed and agree that this is a good way to record decisions as well as to ensure action is taken on given items during each call.

**Comment by whoabuddy** [comment]
Following up on this topic, it would be nice to know *who* is responsible for *what* when it comes to action items. We talk about this briefly on the calls, but I think a written record and a little more emphasis would help us complete more tasks and knock them off the list.

**Comment by lrettig** [comment]
Accountability is our friend! Each task should probably have a single owner

**Comment by whoabuddy** [comment]
Closing this in favor of #62 and the new meeting agenda template that started with call 13 https://github.com/stacksgov/pm/issues/41#issuecomment-631036717
