### ISSUE TITLE
Establish deadline for all written contributions for governance blog #1

### ISSUE THREAD

**Issue by blockstackers** [stacksgov/pm#40]
**Deadline:** Sunday, May 10th at 11:59pm PST

**Comment by whoabuddy** [comment]
@blockstackers I know we covered this in the call - are we ready to close this one? Do you need any more content before we get started on the blog posts?

**Comment by blockstackers** [comment]
@whoabuddy I think we have enough content for the first wave of posts! Will open an issue with suggested topics + proposed deadlines.
