### ISSUE TITLE
Create issue template for meeting agendas

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#42]
We should create a Github issue template for meeting agendas, either in the old format or the new format discussed in Working group call 13 (#41).

This could also be added to and help streamline the [SOP](https://github.com/stacksgov/pm/blob/master/sop.md).

Note: this can be done at the .github repo level for the whole org, but may be better here as agendas are posted to PM by default. I am open to feedback on that.

**Comment by whoabuddy** [comment]
Also, issue labels for "action" and "discussion".

**Comment by lrettig** [comment]
Not sure how others do this, but when I open an issue for a new meeting, I tend to "clone" the agenda for the previous meeting, since there aren't usually too many changes. I'm worried that setting up an issue template might actually make this more complicated. What do others think?

**Comment by joberding** [comment]
I'm all for cloning. There are different levels of experience with GitHub
in the community. Let's not make it more difficult. However, I like Jason's
approach which could streamline the SOP. So, I'm torn. Frankly, I would
like to see more participation on the repo. Guess that needs to be an issue.

**Comment by whoabuddy** [comment]
Closing this out since the meeting agenda template is live and was used for #98 #99 and calls moving forward
