### ISSUE TITLE
Decide on first 2–3 topics of the blog series

### ISSUE THREAD

**Issue by blockstackers** [stacksgov/pm#43]
Suggested topics for the first few pieces:
- **Meet the Blockstack Governance Working Group:** Profile of group members, group ambitions
- **What does governance mean to us?:** Other projects that have inspired us (with a particular focus on unconventional sources of inspiration, e.g. Two Row Wampum Development Council)
- **The Stacks Foundation:** Status of the foundation, brief summary of work undertaken to incorporate, next steps, 2020 vision

**Comment by lrettig** [comment]
I like all of these, and I think they're a great starting point. Some other ideas we might want to explore in the future:

- What we've learned from governance of other blockchain projects
- "Real world" governance examples that we're excited about - some overlap here with the second bullet point above, e.g. Two Row Wampum. Could also talk about things like holacracy, teal organizations, Enspiral, the co-op model, etc.
- Profile a particular question we're debating, or challenge we're facing, maybe by presenting both sides of the story briefly
- Ideas we have about specific projects, such as grants, SIPs process, or App Mining, and where the ideas came from
