### ISSUE TITLE
Governance "landing page"

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#45]
As I mentioned in https://github.com/stacksgov/proposals/pull/12#issuecomment-632811302, the more I think about it, the more I think it would be nice to have a single, canonical governance "landing page" or "start here" page that we can direct newcomers to. The closest thing we have to that today is probably the README at https://github.com/stacksgov/resources/. It could include some basic background information and some calls to action for next steps. Do folks feel that what we have now is sufficient or do we want to think about spinning up something new - and, maybe, simpler/less intimidating?

In the future this could conceivably be stacks.org, or a page under that.

**Comment by joberding** [comment]
> and, maybe, simpler/less intimidating?



Yes to this!

**Comment by whoabuddy** [comment]
I like this idea and it makes sense to me that it would live on stacks.org. 

In addition to the resources readme we also have the [.github contributing](https://github.com/stacksgov/.github/blob/master/CONTRIBUTING.md) file that applies to all repos, but it's very *blah* and could use some updates. 

I'm also debating if the CONTRIBUTING.md file would be a good place for a basic form of navigation, or if we should point back to the landing page as a starting point. Now that the stacks.gov website exists we should probably look at the flow from the zoomed out 30ft perspective again.

Right now, the Governance links on stacks.org go to:

- the stacksgov organization (showing repos)
- the Youtube channel
- the forum category

Each of those is a pretty straightforward action, but if I were looking for the next meeting agenda, the standard operating procedures, or anything more granular it's definitely a challenge to find it!

**Comment by lrettig** [comment]
> I'm also debating if the CONTRIBUTING.md file would be a good place for a basic form of navigation, or if we should point back to the landing page as a starting point

I think it should point to the landing page. For one thing, there's a CONTRIBUTING file per-repo, so it would be a hassle to maintain them all (decentralization ftw!). My idea is that we channel people from basically everywhere else to a single landing page, with a brief explanation, call to action, and links to more resources. All of the CONTRIBUTING and README files should point there, as well as the YouTube channel description, forum category post, stacks.org homepage, etc.

**Comment by whoabuddy** [comment]
@lrettig I agree with the points above, however one small note:

> For one thing, there's a CONTRIBUTING file per-repo, so it would be a hassle to maintain them all (decentralization ftw!).

There shouldn't be! The .github repo provides a single CONTRIBUTING.md used for each repository, and can do the same for all of the community health files. The only thing required per repository is a README and LICENSE :slightly_smiling_face:

**Comment by lrettig** [comment]
@whoabuddy don't they just get cloned as a one-off when a new repository is created, though? Like, updating the community health files doesn't automatically update existing copies across all repos does it?

**Comment by whoabuddy** [comment]
@lrettig No, as long as the file doesn't exist in the repo then it uses the .github version by default, so updates should be shown automatically.

**Comment by lrettig** [comment]
> @lrettig No, as long as the file doesn't exist in the repo then it uses the .github version by default, so updates should be shown automatically.

You learn something every day...

![learn](https://media2.giphy.com/media/ijxKTF6iE4K4M/giphy.gif)

**Comment by lrettig** [comment]
From discord today:

@dantrevino: Regarding the "landing page" discussion here: https://youtu.be/SUASurbAyzI?t=2375 ... I suggest using github pages for building out a website or part of stacks.org ... This allows us to maintain a very open version history, allows easy contribution, and provides an easy user-consumable way to present "final" versions of whatever.  See my comment in https://github.com/stacksgov/pm/issues/33#issuecomment-635500551
lane: thanks for the feedback - I use github pages in a bunch of projects, totally love it. It really depends how the current stacks.org site is set up and how easily this could be integrated. (assuming we want it to be integrated - I suppose stacks.org/governance could just redirect to a separate github pages page, that's okay too)

**Comment by whoabuddy** [comment]
Closing this as we now have github pages setup for both the resources and pm repos
