### ISSUE TITLE
Review draft of blog #1

### ISSUE THREAD

**Issue by blockstackers** [stacksgov/pm#52]
https://paper.dropbox.com/doc/Meet-Blockstacks-Governance-Working-Group--A1IQSIXXiX3Y5osI8CCD77EiAQ-9GkwLxyDUKGe01h9dKvOp

**Comment by HaroldDavis3** [comment]
@blockstackers This looks great! Short form writing in any kind is a completely mysterious art for myself ha so this seems like a beautiful intro piece. TY kindly

**Comment by blocks8** [comment]
Great piece - added comments. Are we ready to move forward? 

Perhaps something to work on for Wednesdays working meeting? @whoabuddy

**Comment by lrettig** [comment]
Reviewed, added comments in the doc as well! Looking good.

**Comment by blocks8** [comment]
Blog post published: https://stacks.org/blockstackgovernancegroup
