### ISSUE TITLE
Governance working group roadmap

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#56]
As I reflect on what we've accomplished to date, and consider where we go from here, I've been thinking about concrete, value-accretive projects that the working group can tackle going forward. Here's a brain dump. Feel free to agree/disagree, add things to this list, etc.

- SIP process
- grants
- app mining
- regular communication, updates, blogging, etc. - translating things that are happening in the ecosystem - see [Ethereum Cat Herders](https://medium.com/ethereum-cat-herders) as an exemplar here
- project management, sharing best practices, helping other working groups/engineering groups set up the things that have worked well for our group (again, see ECH as exemplar)
- keeping a pulse on the sentiment of the community, acting as a liaison between/among community, PBC, and the Foundation
- translation, commissioning translations and managing the process (cf. #32)
- events, town halls, esp. in other languages/timezones
- education: both internal, about blockstack, as well as external, speaking to e.g. college students
- soliciting contributions to core codebase, documentations/video guides/howtos/streams
- serving as a "help desk" for folks in the community who don't know where to go for help with things (see ECH as exemplar)
- serving as an "entry point" for folks who are new to the community and want to contribute but don't know how (see ECH as exemplar)
- soliciting help from outside subject matter experts eg primavera (cf. #38)

**Comment by lrettig** [comment]
Thanks for renaming - as discussed on yesterday's call, the main task here is to figure out priorities and deliverables - basically, a roadmap - going forward.

**Comment by HaroldDavis3** [comment]
@lrettig Ty kindly for the comprehensive list. Will add the following for now & hopefully **add more soon:**

- Collections

- Establish internal ongoing & elaborated governance R+D Workflow that can culminate external workshops & conf akin to RadicalxChange format.

- Legal resources for gov't WG community. (..though Juliet is all we'll ever need. 💯  )

**Comment by whoabuddy** [comment]
Closing in favor of #149  - will cover through that initiative.
