### ISSUE TITLE
Archive survey results

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#59]
We should add the results of the survey to our knowledge base - probably, the resources repository. The anonymized, randomized results are [here](https://docs.google.com/spreadsheets/d/1as9eBTvU8HYKtGVQjsPaig_kJOGeshmSEckBbtXmR_0/edit?usp=sharing). We may also want to include a nicely-formatted report, as well as my own [analysis](https://docs.google.com/document/d/1mno__NyNw3DMf13SO_CSvpXeGrHAHek49neOIHeju20/edit?usp=sharing).

**Comment by lrettig** [comment]
Opened a PR for this: https://github.com/stacksgov/resources/pull/42

**Comment by whoabuddy** [comment]
Closed in favor of [stacksgov/resources#42](https://github.com/stacksgov/resources/pull/42)
