### ISSUE TITLE
Following up with survey respondents

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#60]
Per https://github.com/stacksgov/pm/issues/1#issuecomment-632899031, we probably want to follow up with survey respondents - to invite them to participate in the governance working group, share resources and updates, etc.

**Comment by lrettig** [comment]
Created a draft here. I could use help reviewing it, and filling in the placeholders. https://www.dropbox.com/scl/fi/87ovxpxoycaehvczjh8sl/Survey-followup-email.paper?dl=0&rlkey=a11ofx09h4d8u3v4j9vo9hwnv

**Comment by lrettig** [comment]
Updated draft and factored in the most recent feedback. Thanks to everyone who provided feedback. We are still waiting on a couple of things to send this -- for the blog post (#52) to be published, and for more information on the town hall.

**Comment by lrettig** [comment]
I think this is in pretty good shape. I cleaned up the copy a little and added a link to the recently-published blog post at stacks.org. Still need more info on the call to action here - I think we decided to invite folks to a town hall (#68).

**Comment by whoabuddy** [comment]
Closing this issue as discussed during #99, we missed the window to reply to survey respondents while remaining relevant, but we can use this list as a resource for future announcements moving forward. 

@jennymith pointed out it would be nice to relay accomplishments of the working group, and/or to highlight information about something such as the grant proposal. Any ideas are welcome as new issues!
