### ISSUE TITLE
Meeting Roles, Responsibilities, and Bounties

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#62]
## Meeting Roles and Responsibilities

Looking back over the conversation in call 16 (#58), I would like to propose the following scenario to help streamline the action items and record-keeping that goes along with each call.

As part of the [standard operating procedures](https://github.com/stacksgov/pm/blob/master/sop.md), I propose we add two standard roles for each meeting, and please comment with any feedback!

## Meeting Moderator

We already assign this from week to week, but as of late it gets decided last minute. The goal is to keep this as an unpaid position that *anybody* can jump in to take care of, and we have done our best to rotate moderators up until now.

Based on the list below, access to the paid Zoom Pro account for the foundation would be the only prerequisite, and I like the idea of deciding the next week's moderator as the first order of business.

- could be decided at the beginning of each call for next week?
- shares the agenda with the group ~24hrs before the meeting
- shares the agenda with the group before the meeting starts
- sets up the call on Zoom as host and shares the link before the meeting starts
- walks the group through the agenda and discussion points

## Meeting Secretary

This would be a new role similar to what I have done in the past with notes, but breaks up the tasks so that they are only required during the meeting and directly after.

Given the amount of work listed below and the goal of creating a consistent experience, I think this position would be eligible for a small bounty. We can add rules for rotation or anything else necessary to keep it fair between all participants.

- could be decided at the beginning of each call for next week?
- takes high-level, simplified notes based on the agenda topics
    - i.e. agenda Item --> summarized responses / assigned actions
- shares the notes via comment in the related agenda issue at end of call
    - see example [from call 16](https://github.com/stacksgov/pm/issues/58)
- creates a new agenda for the following week (mostly copy/paste)
    - could update based on action items, removing completed items, etc
- uploads the Zoom recording to Youtube for reference based on SOP
- shares the Youtube video link in the working group chat and update it in agenda issue
- uploads the video transcript to the resources repo based on SOP
- uploads the chat transcript to the resources repo based on SOP
- updates links in the resources repo based on SOP

## Further Updates 

Additional tasks that may warrant their own bounty include:
- creating an official "update" based on the secretary's notes, that could be published to the forum, to the blog, or used in other outlets. Similar to [these updates published in the past](https://github.com/stacksgov/updates) and [this forum post from Juliet](https://forum.blockstack.org/t/governance-working-group-update-april-29-2020/10754).
- cleaning up the transcription notes, including fixing "bloopers", fixing split lines/sentences, and possibly reviewing the transcript against the video itself
    - note: this would be a great paid task for someone watching the video after the meeting, as they could both consume the content and update the notes without having to go through the entire meeting a 2nd time, and receive a small bounty in doing so.

**Comment by HaroldDavis3** [comment]
Sounds good. Beautiful for horizontal dynamics too. Happy to fall into any of these rotations when needed. :100:

**Comment by joberding** [comment]
"creating an official "update" based on the secretary's notes, that could be published to the forum, to the blog, or used in other outlets. Similar to these updates published in the past and this forum post from Juliet."
@whoabuddy Happy to do "official updates" to forum.

**Comment by joberding** [comment]
"creating an official "update" based on the secretary's notes, that could be published to the forum, to the blog, or used in other outlets. Similar to these updates published in the past and this forum post from Juliet."
@whoabuddy Happy to do "official updates" to forum.

**Comment by blocks8** [comment]
We don't currently offer a bounties program but these types of tasks could be a good use of them down the line, especially if the bounties are denominated in STX.

**Comment by whoabuddy** [comment]
Closing in favor of #80 and #81
