### ISSUE TITLE
Configure github pages for resources

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#69]
Per #45, we want to implement [GitHub Pages](https://help.github.com/en/github/working-with-github-pages/about-github-pages) and [Docsify](https://docsify.js.org/#/) to provide a general landing page for the governance resources.

Docsify will allow us to generate documentation content based on the markdown files and folder organization already in the repository. 

The information should be accessible both on Github and at [resources.stacks.org](https://resources.stacks.org).

After implementing this for resources, we can use the configuration as a template for other repositories.

**Comment by lrettig** [comment]
As @whoabuddy and I discussed offline, I think the main challenge here is in writing, and organizing, our content - a task that I believe he already started! The technical challenge of setting up gh-pages and something like docsify to publish it is not so great, I think.

**Comment by whoabuddy** [comment]
Closing this as the main structure including github pages and docsify are set up, and the structure of the repo translated fairly well. There is still some organization to do, but it can be handled in separate issues.
