### ISSUE TITLE
Remove issues and projects tabs from other repos

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#76]
Considering this repo is for project management and related issues, we should update the other repos so that they no longer have an issues or projects tab. This will help funnel those efforts here for a single place to manage things.

**Comment by whoabuddy** [comment]
Progress:
- [x] stacksgov/resources
- [x] stacksgov/community
- [ ] stacksgov/proposals (11 open issues now)
- [x] stacksgov/updates
- [x] stacksgov/.github

The only one I didn't do is the stacksgov/proposals repo, and I'm not sure what to do with those issues.

Should we move them to pm and tag them accordingly? That seems like the easiest course of action for now.

Will this repo eventually be archived in favor of the new SIP process outlined in stacksgov/proposals#1 and [stacksorg/SIP-000](https://github.com/stacksorg/sips/blob/master/sip-000/sip-000.md)?

**Comment by lrettig** [comment]
> The only one I didn't do is the stacksgov/proposals repo, and I'm not sure what to do with those issues. Should we move them to pm and tag them accordingly? That seems like the easiest course of action for now.

Hmm. I sort of think of the proposals repo a little differently. Most of those issues should in time evolve into pull requests focused on specific documents, or specific portions of documents, that live in their own repo. Maybe it should be called "constitution." Or maybe as you indicate it should be merged with the SIP process.

**Comment by whoabuddy** [comment]
All repos are updated based on the criteria above save stacksgov/proposals per Lane's feedback above. Closing this out and we can review what to do with the proposals repo as a separate issue.
