### ISSUE TITLE
General Stacks Foundation information structure

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#77]
We have an awesome list of resources in the [resources repo readme](https://github.com/stacksgov/resources/blob/master/README.md), now available online at https://stacksgov.github.io/resources, and plenty to add/expand this with in #70 and #73.

As we add/expand this area, I'd like to consider two things: how does this fit into the "bigger picture" of organized information as the foundation forms, and how do we prevent this from becoming an impossible-to-digest long list of even longer articles without context?

**Comment by whoabuddy** [comment]
To try and answer this, as well as reorganize the information in a useful fashion, I created the following outline of how I perceive the structure to be now. If we like where this is headed, I can propose some changes in how we group the information, a lot of which can translate to the docsify/github pages site for easier viewing/interpretation.

> “It is important that we know where we come from, because if you do not know where you come from, then you don't know where you are, and if you don't know where you are, you don't know where you're going. And if you don't know where you're going, you're probably going wrong.”
> ― Terry Pratchett, I Shall Wear Midnight (found via [goodreads.com](https://www.goodreads.com/quotes/317062-it-is-important-that-we-know-where-we-come-from))

-----

# Stacks Open Internet Foundation

## Stacks Website (stacks.org)

- Registrar: NameCheap (https://namecheap.com)
- Name Servers: Cloudflare (https://cloudflare.com)
- Hosting: Tilda (https://tilda.cc/)
- Email: Google G Suite (https://gsuite.google.com)

### About

- What we do
    - Governance
    - Research
    - Education
    - Grants
- Who we are
    - Stacks Foundation Board
        - Zavain Dar
        - Rodolfo Gonzalez
    - Stacks Foundation Team
        - Brittany Laughlin
        - Jude Nelson

### Blog

- Blog Posts

### Email List

- Based on TildaCDN

### Community

- Forum: https://forum.blockstack.org/c/Working-Groups/governance
- YouTube: https://www.youtube.com/channel/UCirhluDUpSPVMZQn210HETg
- Twitter: https://twitter.com/StacksOrg
- Discord: https://discord.gg/HsK3ShU
- Telegram: https://t.me/BlockstackChat

## StacksOrg GitHub (github.com/stacksorg)

### SIPs

- SIP-000

### Stacks Blockchain

- future home of all stacks 2.0 blockchain repositories moved to the foundation's control

## StacksGov GitHub (github.com/stacksgov)

### Resources

- readme
    - Stacks Governance
        - Get Involved!
        - Governance Calls
        - Governance Survey
        - Interview Notes
        - Github Repositories
        - Blockstack Community Forum
    - General Blockchain Governance
        - Articles / Websites
        - Documents
        - Examples
        - Videos
    - Other Governance Resources
        - Open Source Software Articles
        - Open Source Software Examples
        - Commons, Consensus, and Decision-making

#### Brand

- icon

#### Calls

- readme
- canonical notes

#### Interviews

- readme
- interviews

#### Survey

- readme
- related files

### Community

- readme
- usage TBD
    - used for community board seat and related items?

### Project Management (pm)

- readme
- projects
- issues
    - agendas
    - action items
    - discussion items
    - notes
    - additional tasks
- standard operating procedures (sop)

### Proposals

- readme
- issues
    - initial governance proposals

### Updates

- readme
- canonical updates

### .github

- community health files for the STACKSGOV organization
    - CONTRIBUTING.md
    - TBD: CODE_OF_CONDUCT.md
    - other possibilities, based on the [GitHub help article](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file)
        - FUNDING.yml
        - Issue and pull request templates and config.yml
        - SECURITY.md
        - SUPPORT.md

**Comment by paradigma-cl** [comment]
I had a look at them and could not suggest any better.  The structure sounds coherent.  Probably the use will give us some more feedback.

**Comment by joberding** [comment]
I really like this format - it looks clean and easy to read. Agree with @paradigma-cl that use will give more feedback. LGTM.

**Comment by blocks8** [comment]
This looks good. I think if we can create pages with different categories, ie: Resources, Content, etc. then we'd be able to group these things so it's accessible depending on what you are looking for.

Very well organized! What do you need next to push this forward?

**Comment by whoabuddy** [comment]
Most of this was implemented as part of adding docsify in #87 and changes made in stacksgov/resources#48, and future changes/recommendations can be documented in new issues.
