### ISSUE TITLE
Fix opengraph data for individual repos

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#78]
Right now the organization has a community-created logo stored in the stacksgov/resources repo.

![Screenshot from 2020-07-08 09-34-01](https://user-images.githubusercontent.com/9038904/86945980-93ac7300-c0fe-11ea-8a46-6264240595bb.png)

However, when linking to issues in an individual repository, the default github logo is displayed:

![Screenshot from 2020-07-08 09-34-27](https://user-images.githubusercontent.com/9038904/86946064-ad4dba80-c0fe-11ea-86d4-75c4cc25d974.png)

**Comment by whoabuddy** [comment]
I tried updating the **Social preview** setting using a new logo referenced in stacksgov/resources#46, following the [GitHub help guide here](https://docs.github.com/en/github/administering-a-repository/customizing-your-repositorys-social-media-preview).

![2020-07-08 09 38 18 github com 9c8f9b5c958f](https://user-images.githubusercontent.com/9038904/86946242-f69e0a00-c0fe-11ea-8577-d1585ad36bb0.png)

So far it is not working, but I am wondering if it takes time to update? How else can we fix that generic icon?

**Comment by whoabuddy** [comment]
After being patient and testing again, this is working correctly, so I added it to all other repos and saved the changes today. Closing this issue, and if we want to update the image and/or add text or some content per repo, we can do that in a separate issue.

**Comment by lrettig** [comment]
Very cool! Thanks for doing this. Agree that it's important for brand :)
