### ISSUE TITLE
Role: Meeting Secretary

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#80]
Per #62, this was agreed upon as a good idea among the group, so both of the roles that were "bounty candidates" for the future are now separated into its own issue for further discussion of responsibilities and tracking.

## Meeting Secretary

This would be a new role similar to what I have done in the past with notes, but breaks up the tasks so that they are only required during the meeting and directly after.

Given the amount of work listed below and the goal of creating a consistent experience, I think this position would be eligible for a small bounty. We can add rules for rotation or anything else necessary to keep it fair between all participants.

- could be decided at the beginning of each call for next week?
- takes high-level, simplified notes based on the agenda topics
    - i.e. agenda Item --> summarized responses / assigned actions
- shares the notes via comment in the related agenda issue at end of call
    - see example [from call 16](https://github.com/stacksgov/pm/issues/58)
- creates a new agenda for the following week (mostly copy/paste)
    - could update based on action items, removing completed items, etc
- uploads the Zoom recording to Youtube for reference based on SOP
- shares the Youtube video link in the working group chat and update it in agenda issue
- uploads the video transcript to the resources repo based on SOP
- uploads the chat transcript to the resources repo based on SOP
- updates links in the resources repo based on SOP

**Comment by BaiHuLaoShi** [comment]
Hi, folx,

On a call with Dan, Juliet, and others, I accidentally volunteered for this Issue before I even knew it was an open item. 

Happy to discuss performing the role pro bono while we figure for fit and final details.  While new to the community, I'm a quick study with ample free time.  It sounds like this might be a small, helpful win on the road to transparent governance.

Thoughts welcome; otherwise, I will catch everyone on Discord.

**Comment by whoabuddy** [comment]
@BaiHuLaoShi Thank you for your interest! Notes are really helpful for those that watch the video later or prefer to read over watching the videos.

To give you some back story on this:
- the full list of past calls for the Governance Working Group is [here](https://stacksgov.github.io/resources/#/calls/?id=governance-working-group).
- initially, we typed up notes from each meeting in detail (i.e. [Call 6](https://stacksgov.github.io/resources/#/calls/notes/2020-04-01-Meeting-0006)), but it became difficult to keep up with the pace of the meetings, and generally required watching the recording again.
- we started using the Zoom transcription service for meetings around [Call 12](https://stacksgov.github.io/resources/#/calls/notes/2020-05-13-Meeting-0012), which provided a good mix of content and interesting typos. This also created a bit of a mess, as now notes exist in a few forms:
  - there are edited transcripts, which still require watching the recording to fix small issues (i.e. Call 12)
  - there are unedited transcripts, but in trying to remove the timestamps, line breaks were removed as well (i.e. [Call 14](https://stacksgov.github.io/resources/#/calls/notes/2020-05-27-Meeting-0014))
  - there are unedited raw transcripts, which have excessive line breaks, time stamps, and do not render correctly (i.e. [Call 32](https://stacksgov.github.io/resources/#/calls/notes/2021-01-21-Meeting-0032))

Right now I am working through stacksgov/Stacks-Grants#30 to update the repositories, standard operating procedures, and bring everything back up to date. Some things that would be really helpful in order of priority:
- reviewing any old videos that do not have notes then create them
- taking notes during a call, that could be posted as a summary (i.e. [Call 20](https://stacksgov.github.io/resources/#/calls/notes/2020-07-20-Meeting-0020))
- cleaning up any transcripts for typos, formatting

As far as the bounty, this did not fit in directly with the beta grants program but I am open to any ideas, suggestions, or proposals to what would make it fair, as well as with any of the items listed above. The goal is to keep things simple, but to provide as much info for the public as possible!

**Comment by BaiHuLaoShi** [comment]
Agreed re: accessible, maintainable transparency for the public.

No ideas yet, don't know what I don't know, definitely more as we go. The context kickstart is super helpful, thank you!

The low hanging fruit is easy for me and others to grab. Good stuff to get the ball rolling and get folx familiar.

**Comment by BaiHuLaoShi** [comment]
The above was ambiguous on my reread.

I will shoot for by the next Thursday Governance meeting:

- writing summaries for the missing notes with available video, 
- cleaning up the formatting of existing transcripts, with initial proofing 
- using this to improve my live notetaking skills before next Governance meeting

**Comment by Brexton017** [comment]
Hi All,
I'll be helping Tony out with clearing out some of the the backlog items for updating the repositories.

**Comment by Brexton017** [comment]
I've cleaned up all the formatting of the notes from meetings 14-32 (13, 15 and 18 are not yet transcribed). I have them in RTF format. The next step would be to compare them to the videos for clean up: clearing out the paragraph breaks due to pauses, correcting transcription errors, and generral clean up. If there is somewhere I should post in the in progress files, please let me know.
Thanks!

**Comment by joberding** [comment]
@Brexton017 Absolutely awesome work. Thank you!

**Comment by whoabuddy** [comment]
@Brexton017 I appreciate your help with this!! I am happy to review any of the content and get it into the correct format to include in the repo. Are you on the Stacks Discord? If so, dm me there, my username is also `@whoabuddy` :raised_hands:

**Comment by whoabuddy** [comment]
Closing in favor of #181
