### ISSUE TITLE
Working Group - Retrospective Call on July 20 at 12:30pm ET

### ISSUE THREAD

**Issue by blocks8** [stacksgov/pm#82]
### Meeting Details

- Date/Time: July 20 at 12:30pm ET
- Location: Link will be posted in #governance working group channel on Discord shortly before the call.
- Recording: Zoom
- Moderator: Jenny
- Secretary: TBA
- Publisher: @blocks8 

### Discussion Topics
We'll address the lessons learned and opportunities going forward for our weekly Governance Calls. Including, what's worked well in the past, where there is opportunity, how to schedule going forward, and ways to move issues forward faster going forward. 

Open Discussion (please bring ideas to the meeting or submit as a comment below):
- Potential new meeting times
- What role the gov working group would like to play in leading community governance moving forward
- How we would like to work together moving forward (i.e. subgroups/workstreams? biweekly check-ins?)
- The gov working group's relationship with the foundation

Deeper considerations:
- What are the most impactful community issues that we can take on? We'll collaborate on a list. 
- What do we need to be productive? (i.e. Specific tools, external expertise/advice)

**Comment by ryanarndtcm** [comment]
I was on today's call and took some notes.
**Summary of call**
- The Stacks Foundation will have a small staff with the goal is to help empower other working groups/communities to do that which supports the mission of the Foundation.
- The Stacks Foundation could encourage publishing of certain ideas - but does not want to be the sole carrier of the mission. Policies will need to align in that area, but the onus will not be on the Foundation alone. It's not top down but more like feeding the grassroots. It is also still early days in the creation of the organization.
- The Governance Working Group will act independently of the Stacks Foundation or Blockstack PBC.
- The Governance Working group will act as an independent advocate for the broader community, but will need more data (surveys etc) and community involvement to do so.  
- The Governance Working Group will apply for a grant related to specific tasks.
- The grant program gives transparency and accessibility as well as get more involvement and buy in from community
- Collections is very important to the broader community and to the sustainability of web 3.  Radiks/collections will likely be on the first grant. 
- Another possible area is to help give developers guidance on writing their dapps for privacy - re: privacy shield ruling https://www.wired.co.uk/article/privacy-shield-ruling )
- Grants could be approached in a number of ways, Lane suggested that 1) the Governance Working Group could apply for own grant. 2) GWG could apply for a "meta-grant" to give grants to others 3) GWG could be part of the grant approval process
- Grants could have 3 month goals working with community directly - if goals were met - more funding could be applied to/accessed. This grant time limit will keep the working group accountable, independent, and focused on community goals.
- The grant process will be starting roll out soon (around August 3rd, 2020) via grants.io and will start with amounts less than USD$5000.
- GWG will have access to a draft of the application to prepare in advance of the launch. The created grant will act as a beta test of the application and approval process.
- Meetings will continue, though the timing may change. Lane is sending out a form for attendees to complete to help organize a best time going forward. The goal going forward will to be to allow easier access for people around the world.
- Jenny will start a shared document to help manage potential grant ideas asynchronously as 10ET is very early for some attendees. Asynchronous work will help manage that challenge with action items discussed on calls, and subpoints worked on async.

**Comment by whoabuddy** [comment]
This represents call 20, and closing in favor of #84
