### ISSUE TITLE
Grants Application - Draft

### ISSUE THREAD

**Issue by blocks8** [stacksgov/pm#85]
Request for feedback on the Grants Application process. This is the draft for our beta grants program that we'll run in Q3 to ensure a smooth process, quality applications, and the opportunity to fund awesome initiatives in our ecosystem. 

Specific feedback requests: 

- Application template: Are there things that are unclear? Is there missing categories of information? 
- Application process: All applications will have feedback in 7 days. Grants will be reviewed for approval twice a month. Does that cadence sound right? We'll approve on a set cadence, so it shouldn't be longer than 14 days from application. 
- Grants committee: We could open this up to a community board for first feedback and approval. We'll start small but something to consider.

------------------------------------------

## Stacks **Grants**

The Stacks Foundation grants program looks to further our mission by funding technology, research, and contributions that create a user owned internet. We want to encourage meaningful contributions to the Stacks ecosystem and are requesting proposals that fall into one of the following:

- Increase education, adoption, and development of the Stacks blockchain
- Make improvements to the Stacks blockchain protocol or developer tools
- Improve tools and resources for STX holders, developers, and end users
- Grow awareness and advocacy for a user owned internet

**Grant Applications**

Grant applications should clearly outline the project's purpose, who benefits, how the project will serve the mission, a measurable outcome, relevant experience from the individual/team, risks, and links to community input, research, or supporting work relevant to your project. 

The grants proposal process was designed for input from the community. Applications are a part of the conversation with the STX ecosystem to seek feedback, input and collaborators. Applicants may benefit from presenting their idea in a blog post, video demo, or forum discussion to get more input and feedback. We strongly encourage applicants to consider how to continue sharing proposal updates, progress, and final deliverables with the community over time. 

**Application Template**

*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

- Background
    - What problems do you aim to solve? How does it serve the mission?
- Project Overview
    - What solution are you providing? Who will it serve?
- Scope
    - What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
- Team
    - Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?
- Risks
    - What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
- Budget and Milestones
    - What grant amount are you seeking? What milestone deliverables can you provide during your project?
- Community and Supporting Materials
    - Do you have previous projects, code commits, or experience that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

**Grant Amounts**

Our beta grants program will award grants in the range amount of $50 to $5,000 in USD or equivalent. 

Grant proposals with a larger scope may scope milestones into maximum $5,000 amounts but must make sure each milestone has a measurable deliverable. Preference will be given to projects that can successfully complete a sub-$5,000 grant first before applying to larger grants later on. 

**Requirements**

- Must further the mission of a user owned internet
- Contributions must be open source
- Grantees must verify their ID and sign a contract to obtain funding, restrictions may apply to citizens of OFAC countries

**Application Process**

- Sign up for the Stacks Grant website (link coming soon)
- Submit your application and relevant links, materials, and mock-ups
- [Optional] Share your submission with the community for comments and feedback
- The Stacks Grants committee will accept for review, request more feedback, or pass within 7 days
- Accepted applications will be reviewed for approval
- Approved grants are provided grant contract, upon signature, grants are funded
- Passed applications can reapply with edits or solicit donations and support from the community

**Comment by paradigma-cl** [comment]
I would like to suggest to consider a broader scope for the objective: Increase education, adoption, and development of the Stacks blockchain.  It could be something like this:  Increase education, adoption, commercial, technical capabilities and development of the Stacks blockchain ecosystem and it inner participating ecosystems.
For the objective: Grow awareness and advocacy for a user owned internet, I would like to suggest: Grow awareness and advocacy for a user owned internet and its inherent values of cooperation and reciprocity.

**Comment by whoabuddy** [comment]
I feel like my contributions below warrant some research into how other foundations currently do this, as well as looking back on some articles and discussions we have had in Discord about other project's successes and failures, but I wanted to list my initial reactions while I had some time. :memo: 

-----

For the categories, it would be nice to add a bullet point for "increased decentralization, data resiliency, and data portability". Things that come to mind immediately are community-led gaia hubs or the continuation of concepts like collections and radiks. 

Basically, anything that eliminates a single point of failure or encourages collaboration / cooperation as @paradigma-cl mentioned.

> Application template: Are there things that are unclear? Is there missing categories of information?

I think this will be easier to answer as we see the first few items flow through, or if we were to try and draft a grant or two as a test, but on the surface it appears to capture a good amount of information that would be usable for both decision making and tracking implementation. 

We could try that with the ideas proposed in [this shared doc from Jenny](https://paper.dropbox.com/doc/Gov-Group-Grant-Proposal--A402pAn8MQVQPIikglkCKxXXAQ-RN1efxJdptsRGVrJIbwou).

> Application process: All applications will have feedback in 7 days. Grants will be reviewed for approval twice a month. Does that cadence sound right? We'll approve on a set cadence, so it shouldn't be longer than 14 days from application.

I don't see an issue with a set cadence, and we can use lessons learned from [setting up the SIP process](https://github.com/stacksorg/sips) to govern [workflow](https://github.com/stacksorg/sips/blob/master/sip-000/sip-000.md#sip-workflow), i.e. *under what conditions can a grant be resubmitted*.

> Grants committee: We could open this up to a community board for first feedback and approval. We'll start small but something to consider.

How would this committee fit in with the current bylaws, and how would its members be selected?

**Comment by lrettig** [comment]
I think this is perfectly reasonable as a starting point! Here are some additional thoughts:

> Application template: Are there things that are unclear? Is there missing categories of information?

LGTM!

> Application process: All applications will have feedback in 7 days. Grants will be reviewed for approval twice a month. Does that cadence sound right? We'll approve on a set cadence, so it shouldn't be longer than 14 days from application.

This sounds reasonable. (See note below about small grant amounts.)

Will this review process happen transparently, e.g., here on GitHub?

> Grants committee: We could open this up to a community board for first feedback and approval. We'll start small but something to consider.

I like this idea.

> We want to encourage meaningful contributions to the Stacks ecosystem and are requesting proposals that fall into one of the following:

Consider adding a "wildcard" category here - something along the lines of, "Propose a project that you believe will add value to the ecosystem and explain why"

> What problems do you aim to solve? How does it serve the mission?

What mission? (This is answered below, but the text could be structured a little better.)

> Contributions must be open source

Consider requesting a permissive license as well - open source by itself doesn't get you that far.

One additional comment: While this application makes sense for a larger grant amount, say, > ~$500, it might still discourage certain individuals or teams from applying, especially for smaller amounts. (Here is a [partial list of reasons](https://www.etherean.org/blockchain/economics/2020/05/10/the-problem-with-grants.html#fn:2) why this might happen.) Consider a slightly simpler, faster application for the very smallest grant amounts. One way to do this is via something like a hackathon, where all participants who submit working code that's relevant to the mission are guaranteed some minimum dollar amount of prize money.

**Comment by joberding** [comment]
First, I agree with @paradigma-cl  re a broader scope for the objective and also with @lrettig re wild card.

I want to emphasize how important it is to propose and then build something that keeps in mind the mission of "Can't Be Evil". In App Mining, we saw the problems of a lack of connection with that mission from app miners who continued to use Google analytics instead of creatively building for a user owned internet. Grant proposals should present a deep connect with what it means to develop for a user owned internet and the Can't Be Evil ethos.

**Comment by blocks8** [comment]
Thank you for all of this feedback! Here are the proposed updates to the categories: 

- **Education, Evangelism, and Collaboration.** Are you experienced in communication, marketing, community or creative? Create resources that support or grow the community.  ex: videos, documentation, tutorials, workshops, working groups, etc.)
- **Core Protocol Development.** Are you an experienced blockchain developer or computer science researcher? **** (ex: alternate implementations, contributions to stacks-blockchain reference implementation, etc.)
- **Tools and Services.** Are you a web developer interested in building tools that make the protocol easier to interact with? Are you interested in increasing decentralization, data resiliency, and data portability? Can you build tools and services that make it easier for miners, developers, and tokenholders to interact with STX? (ex: a Rosetta API gateway, STX Stacking wallet, STX custody solutions, alternate explorer, custom mining tools / dashboards, chain visualization / analytics, etc.)
- **Wish list or Wildcard**. Ready to contribute but not sure were to start. We're crowdsourcing ideas from across our ecosystem that best serve our mission. Check out our wish list for ideas or create your own proposal for a project you believe will add value to the ecosystem and explain why.

**Comment by blocks8** [comment]
I've also complied research on grants in this public forum post: https://forum.blockstack.org/t/designing-the-stacks-grants-process/11141

**Comment by SmartMirlo** [comment]
Regarding "Education, Evangelism, and Collaboration", I am considering building a program addressing end-users from my personal experience with a few Blockstack dapps.I am not a technical person, so I am focusing on adoption by the general public, including entrepreneurs, but not developers... I just wonder if this is also considered here, or you are thinking of growing the developers' community.

**Comment by ryanarndtcm** [comment]
@SmartMirlo I am definitely interested to hear more about end user experience. That is an area I have a lot of interest in supporting growth and making ecosystem adoption easier for dapp users/stacksholders/every day folks.

**Comment by SmartMirlo** [comment]
Great! I'll try to bring a good proposal... I am a dapp user/stacksholder/every day folk, and I am eager to share my experience. In the past months I have slowed down my evangelist activities because I have to focus in building my DApp, but now with a bit of support I think I could prepare a series of decks for webinars and small group presentations, or workshops whenever it´s possible.

**Comment by friedger** [comment]
I wrote a test application for the gaia inbox project: https://paper.dropbox.com/doc/Stacks-Grant-OI-Calendar--A6ygq0bG6YJqSojuLkFAxUoJAQ-CupKS46cmNeEPNbxSadrt

For the structure, I would move the "Risks" between "Scope" and "Team". While writing Scope and Risks where very connected.
The only question, I couldn't answer was in the "Background" section the 
> How does it serve the mission?
Refers "it" to the problem that the applicant wants to solve?

**Comment by whoabuddy** [comment]
Closing this after discussion in #98, grants are live on GitHub!
