### ISSUE TITLE
Restructure work streams and information

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#86]
After discussion in #84 there was consensus over reorganizing some of the information into easier to digest categories, moving [action items]() and [discussion items]() into living documents within the repository and on a similar website.

In order to do so, these are some tasks I believe need to happen (and will start developing in a PR):
- [x] setup GH pages for the stacksgov/pm repository
- [x] setup docsify theme to match stacksgov/resources repository
- [x] update contents of stacksgov/resources README to point to pm for project management
- [x] update contents of stacksgov/resources so that research is separated from the main page
- [x] update contents of stacksgov/pm README to point to resources for reference material

From there we can consider items such as those mentioned in #77, #73, and #48, as well as what to do with the stacksgov/proposals, stacksgov/updates, and stacksgov/community repositories.

**Comment by whoabuddy** [comment]
The two PRs listed above (#87 and stacksgov/resources#47) should be a good start toward completing these objectives, and I figure we can always refine it more later. Let me know if anyone has any questions / issues and will wait for approval from at least two people before merging!

**Comment by lrettig** [comment]
Thanks for doing this! Will review ASAP, have a few things in my GH review queue at the moment!

**Comment by joberding** [comment]
Just seeing this @whoabuddy . Will take a look after the meeting today

**Comment by whoabuddy** [comment]
Note: created an emoji vote in Discord on 8/20 to `@everyone` and sent a reminder to `@here` on 8/21:

> :ballot_box: emoji vote for issue #86 (https://github.com/stacksgov/pm/issues/86): I have completed the tasks and would like to merge these changes but wanted to check in with everyone else first, please indicate with a :ballot_box_with_check: or a :no_entry_sign: and I will collect the results tomorrow at 12pm PDT (GMT-7) and record them in the related issue.

Final results were:
- :ballot_box_with_check: from Harold @HaroldDavis3 
- :ballot_box_with_check: from Jenny @blockstackers

I think we have enough consensus to move forward with the changes once the PRs are approved.

**Comment by whoabuddy** [comment]
Both PRs are officially merged! :tada: 

Closing this and will create new issues as needed for content updates.
