### ISSUE TITLE
Open up grant proposal brainstorming process to broader community

### ISSUE THREAD

**Issue by blockstackers** [stacksgov/pm#88]
@joberding expressed some valid concerns about making the Governance Working Group's grant proposal process more transparent and accessible to the broader Stacks community.

As such, it has been proposed that we do the following:
- Invite all Stacks community members to contribute to the grant proposal brainstorming process (roughly outlined in [this collaborative doc](https://paper.dropbox.com/doc/Gov-Group-Grant-Proposal--A5KIht1Zo~DhXHZ5rWPDCCe5AQ-RN1efxJdptsRGVrJIbwou))
- Host an open community call on 08/13 to ensure that community members are aligned on the goals of the grant proposal

By EOD on 08/07, I (Jenny) will be sharing:

- [x] A forum post explaining the goals of the grant proposal, along with instructions on how community members can contribute
- [x] An invitation to an open community meeting (to be scheduled for 08/13) during which we can discuss and align on the goals of the grant proposal

**Comment by lrettig** [comment]
Thanks @blockstackers! Linking #85 here as it's relevant and there's some more commentary there.

**Comment by whoabuddy** [comment]
Closing out this issue as the dates have passed, items are checked off, and the beta program launched!
