### ISSUE TITLE
Community Call 4

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#9]
Date/time: Wednesday, March 18, 2020, 7am PT/10am ET/2pm UTC/3pm CEST/10pm CST ([time zone conversion](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Stacks+Governance+Working+Group+Call&iso=20200311T10&p1=179&ah=1))
**Note the recent timezone change in the USA. Please double-check the time of this call in your locale using the above link!**
Location: Link will be posted in [#governance working group channel](https://discordapp.com/invite/ny6wGkx) on Discord shortly before the call
Recording: https://youtu.be/u8lZsVFCFtc

If you'd like to be added to the recurring calendar invitation, please DM me your email address on Discord.

Proposed agenda (feel free to amend!):
- Quick round of intros
- What happened over the past week?
  - Resources (YouTube/GitHub/Discord/Discourse/others)
  - Regular updates
  - One on one "stakeholder interviews"
- Standup!
  - What is everyone working on right now?
  - Any blockers?
  - What will happen over the next week?
- Community survey
- How to share interview notes
- Preliminary governance proposal
- @dantrevino presentation on open questions
- Stacks Foundation (from PBC)
- Any other updates?
- How to get involved/contribute
  - Resources
  - Regular updates
  - Survey
- Next/recurring call schedule
  - call length and proposal to extend to 90 min (#12)
  - looking for other stewards

**Comment by whoabuddy** [comment]
Add to beginning, quick discussion about call length and proposal to extend to 90 min (#12 )

**Comment by lrettig** [comment]
Added to the agenda, but to the end under the "next/recurring call schedule" topic. Do you think it needs to be upfront for some reason?

**Comment by whoabuddy** [comment]
Moreso to make sure we get to it and get it out of the way, but that makes more sense, lgtm!

**Comment by lrettig** [comment]
Closing in favor of #16
