### ISSUE TITLE
Review and add feedback to grant proposal outline by EOD 08/25/20

### ISSUE THREAD

**Issue by blockstackers** [stacksgov/pm#91]
Hi everyone, I've drafted an outline of the [grant proposal here](https://paper.dropbox.com/doc/Outline-Gov-Grant-Proposal--A6VJiZ5zEsygKObb42jQFrXZAQ-zNybJleQ4Gge82Fw6GEaj) and could really use some feedback ASAP. 

Reminder that we're aiming to submit a final draft of this proposal by 08/27!

**Comment by whoabuddy** [comment]
Closing out this issue as the date has passed and the beta program launched!
