### ISSUE TITLE
Working Group Call #24

### ISSUE THREAD

**Issue by joberding** [stacksgov/pm#96]
Meeting Details

    Date/Time: September 24, 2020 @ 4:00pm UTC / 12:00pm ET
    Location: Link will be posted in #governance working group channel on Discord shortly before the call.
    Recording: TBA
    Moderator: Ryan
    Secretary: TBA
    Publisher: TBA

Standup Updates

What happened over the past two weeks? Standup!

    What is everyone working on right now?
    Any blockers?
    What will happen over the next two weeks?

Stacks Foundation Update

Board Nominations #65

    share list of nominees?
    nominations will stay open for consideration
    could lead to formation of committees or other groups

Community Board Seat #66

    need to decide structure for this, issue is still just a placeholder

Bylaws #63

    are they finalized and should we close issue?

Action Items

Grants Application - Draft #85

Survey: final tasks before completion

    Survey results are archived in the resources repo
    Following up with survey respondents #60

Governance landing page #45

    Github Pages live!
        https://stacksgov.github.io/resources
        https://stacksgov.github.io/pm
    Also: general GitHub cleanup #79 and #76

Meeting conference software selection #14

    request for review and feedback #14 (comment)

Open Discussion

Stacks gTLD Proposal #83

@HaroldDavis3's documents for FabAcademy and Two Row Wampum #54

    Reconstitution Council in conjunction with the 8th New Moon, Sunday, July 9th, 1pm EST
    Stacks Foundation Distributed Network Proposal Issue
    FabAcademy one-pager
    Two Row Wampum Development Council (TRWDC) Proposal Issue
    TRWDC one-pager

Town hall meeting or general public call #68

Governance working group roadmap #56

    SIPs process proposal proposals#1
    Founding Document Review proposals#9
    Code of Conduct proposals#11

Fireside chat series #38

Shared Stacksgov and Blockstack Resources #33

Languages and Translations #32

Establish community observer role for Blockstack PBC research calls #17

@blockstackers community moderation project

Meeting Roles, Responsibilities, and Bounties #62

    defines roles and actionable items for each meeting
    split into issues #80 and #81 for tracking until bounties are available

Resources: bringing notes back up to date

    main table of calls, videos, and notes: https://github.com/stacksgov/resources/tree/master/calls
    Notes for Call 1 and Call 2 resources#15
    Notes for Call 13 #47
    Notes for Call 15 #57
    Raw transcripts for Call 14 / Call 16 / Call 17
        how do we best handle this? create issues for each?

**Comment by blockstackers** [comment]
Will also be sharing an update on the [grant proposal](https://paper.dropbox.com/doc/Stacksgov-Grant-Proposal--A8OVwDQYcrDW_fATb2xbDL~bAg-ke9qLunt5n7WwWwZTV56I) during today's meeting.

**Comment by whoabuddy** [comment]
Closing in favor of #98, with a new format pointing directly back to the issues :slightly_smiling_face:
